# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=20)),
                ('host_lip', models.CharField(max_length=16)),
                ('host_wip', models.CharField(max_length=16, null=b'Ture')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Area')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Group')),
            ],
        ),
        migrations.CreateModel(
            name='servers_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_p', models.IntegerField(null=b'Ture')),
                ('mem_v', models.IntegerField(null=b'Ture')),
                ('cpu_models', models.CharField(max_length=20, null=b'Ture')),
                ('cpu_count', models.IntegerField(null=b'Ture')),
                ('system_type', models.CharField(max_length=20, null=b'Ture')),
                ('disk_total', models.IntegerField(null=b'Ture')),
                ('kernel_version', models.CharField(max_length=32, null=b'Ture')),
                ('lastupdate', models.DateTimeField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Host')),
            ],
        ),
    ]
